// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('2048App').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

//# sourceMappingURL=main.map
